### ISSUE TITLE
Hi !  Is it broken ?  

### ISSUE THREAD

**Issue by gordielachance** [dzafel/pinterest-pinner#21]
Hi, I saw Pinterest changed its website.
Is your code broken since ?
I don't get user informations when doing

`$user = $pinterest->getUserData();`

**Comment by dzafel** [comment]
Yes, it looks like Pinterest team changed an array with user data a little. I have just updated my code. Thanks for reporting it.

**Comment by gordielachance** [comment]
Thanks for your reply.
I still get nothing; here's what I received when I print getUserData() : 

> Array ( [11] => Array ( [display_data] => Array ( ) [placement_id] => 11 [triggerable_placed_exps] => Array ( ) [experience_id] => 14000 [cacheable_resources] => Array ( ) [type] => 1 [id] => 11:14000 [client_context] => Array ( ) ) [10] => Array ( [display_data] => Array ( ) [placement_id] => 10 [triggerable_placed_exps] => Array ( ) [experience_id] => 10000 [cacheable_resources] => Array ( ) [type] => 1 [id] => 10:10000 [client_context] => Array ( ) ) [31] => Array ( [display_data] => Array ( [boardwalk_modules] => Array ( ) ) [placement_id] => 31 [triggerable_placed_exps] => Array ( [0] => 31:500073 [1] => 31:500070 ) [experience_id] => 500070 [cacheable_resources] => Array ( ) [type] => 1 [id] => 31:500070 [client_context] => Array ( ) ) [14] => Array ( [display_data] => Array ( ) [placement_id] => 14 [triggerable_placed_exps] => Array ( [0] => 14:500084 ) [experience_id] => 500084 [cacheable_resources] => Array ( ) [type] => 1 [id] => 14:500084 [client_context] => Array ( ) ) )

**Comment by dzafel** [comment]
Ok, I was able to manually update it to 2.0.7 - you can now use `composer update`
